printer_winter_2017 = """The printer has a master switch which turns the printer on or off. Once the printer is turned on, a user needs to log in before being able to print or scan a document. To login, a user taps her/his printer card on the printer's card reader. Each printer card has a unique ID. If the printer card is authorized, the user can either choose "scan" or "print". If the printer card is not authorized, a login error message is shown.
For the "print" option, the user presses the start button to print the user's first document in the user's print queue. If there is no document in the print queue, an error message is shown instead of performing the printing task. For the "scan" option, the user presses the start button for the printer to scan an original document, which was placed by the user in the automatic page feeder. The scan is sent to the user's email inbox. If the printer does not detect an original document, an error message is shown instead of performing the scanning task. When the printer is done printing or scanning, the user can print or scan the next document. The user may also stop the printing/scanning task at any time by pressing the stop button. The user is allowed to logoff either before or after a printing/scanning task but not while the printer is in the middle of a printing/scanning task.
If there is a paper jam, the printer will suspend the printing/scanning task to allow the user to clear the paper jam. The user may then either cancel the printing/scanning task or resume it. In case the printer runs out of paper during a printing task, the printer suspends the printing task to allow the user to resupply paper. The user may then either cancel the printing task or resume it."""

spa_manager_winter_2018 = """The SpaManager allows saunas and Jacuzzis to be controlled from a central management point. With SpaManager it is possible to turn a sauna or Jacuzzi on and off.
When a sauna is turned on, the stove in the sauna heats until a temperature of 90°C is reached, at which point the stove stops heating until the temperature falls below 85°C and consequently the stove starts heating again. As a safety feature, a humidity sensor monitors the sauna and activates a fan when the humidity exceeds the safety threshold of 40% for more than 3 minutes. The fan turns off automatically after 5 minutes. SpaManager also controls whether eucalyptus-infused water is poured over the stove to increase the humidity. Upon request from the user, a predetermined amount of water is dispersed, if the humidity is below the safety threshold and the fan is not active. At most, water is dispersed once every 15 minutes.
When a Jacuzzi is turned on, the jets of the Jacuzzi eject water at level 1 (the low pressure setting). This can be increased first to level 2 (medium pressure setting) and then to level 3 (high pressure setting). Similarly, the level can be reduced gradually from the highest to the lowest. Furthermore, the user can choose from twenty five different ejection patterns, which determine the order, frequency, and duration of active jets. All ejection patterns work for all three pressure levels. The Jacuzzi comes with a pause feature, which stops the jets from ejecting water for two minutes. The Jacuzzi can also be controlled via a panel attached to the Jacuzzi in the same way as it is controlled remotely from the central management point."""

dishwasher_winter_2019 = """A dishwasher comes with various programs that govern how the dishwasher cleans dishes. The user may select one of the programs, adjust the drying time, and press the start button to start the selected program.
When a dishwasher is started, water is first taken from the water intake pipe. Then, the dishes are washed for 10 minutes and the water is drained. These steps are repeated a certain number of times depending on the chosen dishwasher program. Afterwards, the dishwasher dries the dishes with hot air. By default, the standard drying time of 20 minutes is used. However, the drying time may be extended to 40 minutes at any point during the dishwasher program. The drying time may also be reduced back to the default time but only as long as the drying phase has not started. When the dishwasher is active, its door is locked until the start of the drying phase. It is possible to open the door during the drying phase. When this happens, the drying phase is suspended. The drying phase continues if the door is closed within 5 minutes of opening it. If the door stays open longer, then the dishwasher does not continue with drying the dishes and ends the dishwasher program."""

chess_clock_fall_2019 = """The digital chess clock has six buttons (each of which corresponds to one event): flip (the large white button on the top), minus, plus, startStop, select (the four blue buttons from left to right below the screen), onOff (at the bottom of the clock, not shown in figure).
After turning on the chess clock (with the onOff button), players can iterate through all the (predefined) timings using the plus and minus buttons, and finally select the designated timing by the select button. A timing option has a predefined base time (minutes and seconds) and an increment (in seconds, which can be zero). The game then starts when the startStop button is pressed.
At any time before the game is started, the players can set the clock to match the actual seating of White and Black players using the flip button (e.g. see the placement of the small symbols with the White and Black kings on the screen which can be swapped by pressing the flip button).
When the game is started, White's clock starts counting down (in each second) until the flip button is pressed. At this moment, White's clock stops (and receives a bonus time defined by the increment in the timing option), and Black's clock starts counting down. If the flip button is pressed again, then the same procedure is applied with reversed colors. Both clocks can be stopped by pressing the startStop button, while the game can be continued by pressing the startStop button again. If the clock of the current player counts down to zero, then a flashing flag shall appear on the screen.
The chess clock can be turned off at any time by pressing the onOff button."""

automatic_bread_maker_fall_2020 = """The automatic bread maker has six buttons (each of which corresponds to one event): menu, crust, plus, minus, start, and stop. Furthermore, the bread maker can be turned on and off. The display of the bread maker is out of scope for this state machine.
After turning on the bread maker, a user can select the desired course by iteratively pressing the menu button. The first course is selected by default. At the same time, the user can select the desired kind of crust. The default is medium, which can be changed to dark and then light and then back to medium by pressing the crust button. The bread maker has a delayed start feature, which can be enabled by setting the timer with the plus and minus buttons. Initially, the delayed start feature is not enabled. Each time the plus button is pressed, the timer is increased by 10 minutes up to a maximum of 18 hours. The minus button decreases the timer by 10 minutes.
The start button initiates the baking process or the countdown of the timer in case a timer is set for a delayed start. The baking process consists of the kneading, rising, baking, and warming phases. The various courses of the bread maker differ in terms of their kneading, rising, and baking times. For the kneading phase, a motor is started with the internal startKneading() command. The motor is stopped with the internal stopKneading() command at the end of the kneading phase. During the rising phase, the bread maker does not do anything to the dough. The baking temperature is controlled by the internal heat() command during the baking phase. Each course has a 60 minute warming phase that starts after the baking phase and keeps the bread maker at a set temperature with the internal warm() command. At the end of the warming phase, the bread maker automatically returns to the course selection stage. At any time during the baking process or during the countdown, the stop button also returns the user to the course selection stage."""

thermomix_fall_2021 = """The Thermomix TM6 is an all-in-one kitchen appliance that preps ingredients and cooks them to perfection.
On delivery, the Thermomix TM6 is set to transportation mode. When the selector (button) is pressed to start up the Thermomix TM6 for the first time, the transportation mode is automatically deactivated, and the home screen is shown. To turn the Thermomix TM6 off, hold the selector down for at least five seconds until a message appears to confirm that the Thermomix TM6 is switching off. You can then release the selector. If the Thermomix TM6 has been turned off, pressing the selector turns it back on and the home screen is shown. To save energy, the Thermomix TM6 switches off automatically after 15 minutes when not in use. A message appears for the last 30 seconds, allowing automatic shutdown to be canceled and the home screen to be shown (by selecting cancel on the appliance's screen or by removing the cooking bowl).
To cook a meal, select a recipe on the screen and then select start to follow the step-by-step instructions. First, add ingredients as instructed. The integrated scale weighs them and allows the next step only if the correct amount has been added. Continue to the next step by selecting next on the screen. The Thermomix TM6 chops the ingredients for as long as and at the speed required for the recipe. When the chopping step is done, select next for the Thermomix TM6 to start the cooking step. Again, the Thermomix TM6 cooks the meal at the temperature and time required for the recipe. At the end of any recipe step, the Thermomix TM6 may prompt you to add further ingredients, which are then again weighed, chopped, and cooked. After the last step, the Thermomix TM6 informs you that the meal is ready to be served. When the cooking bowl is removed, the Thermomix TM6 returns to the home screen. It is not possible to cook a meal if the cooking bowl is not correctly placed on the Thermomix TM6.
The selector button raises the following events: selectorPressed (the selector is pressed and released immediately), selectorHeld (the selector is pressed and not released immediately), and selectorReleased (the selector is released after being held)."""

ATAS_fall_2022 = """The Advanced Train Automation System (ATAS) handles the movement of trains across the rail network, i.e., the trains are driverless. The control of the traffic signals, the opening and closing of gates at rail crossings, the setting of turnouts (railroad switches), and the dynamic adjustment of the train's itinerary are out of scope as they are handled by different systems. A train is scheduled several weeks before its departure date, so that passengers can book tickets for the train. The booking process is also out of scope.
The rail network is split into non-overlapping segments. For each segment, the desired train speed is defined. Three types of segments exist: a regular segment, a traffic light segment, and a station segment. The traffic light and station segments also define the coordinates of the location where the train is required to stop (if the light is red or if the station is on the train's itinerary, respectively). While the segments are of variable length, a traffic light or station is always at the end of its segment to allow a train to stop in time if required (i.e., the decision to stop is made when entering the segment). Each traffic light segment or station segment is always followed by a regular segment.
Each train is equipped with three systems that operate continuously and independently of the train as long as the train is active: a Segment Detection System (SDS), a Movement Detection System (MDS), and an Obstruction Detection System (ODS). Each of these systems runs checks every second when a train is active. The SDS detects if the train has entered a new segment and sets the current segment of the train accordingly. The MDS detects if the train is moving or not. The ODS detects whether the railway tracks are obstructed or not and initiates an emergency stop if they are.
At the beginning of its scheduled stop duration, ATAS powers on a train that is waiting at its first station so that the current segment is set to the first segment of the train's itinerary. After the stop duration, ATAS sets the required speed of the train. When the train enters a new segment, the required speed for the segment is set. However, if the segment is a traffic light segment and the light is red, ATAS instead initiates the stopping of the train at the traffic light location. Similarly, if the segment is a station segment, ATAS initiates the stopping of the train at the station location. The actual stopping of the train is confirmed by the MDS in both cases. At a red traffic light, the train waits until the light turns green at which point the ATAS sets the required speed of the train. At a station, the ATAS opens the train doors. The train then waits the scheduled stop duration after which the ATAS closes the train doors and sets the required speed. When the train arrives at its final station, the ATAS waits the scheduled stop duration before powering off the train.
In the case of an emergency, the train stops immediately. You may assume that the train stops in the same segment where an obstruction was detected. Once the train is cleared, the train continues its journey where it left off.
The train is controlled with the help of the following API: setCurrentSegment(segment), setSpeed(currentSegment.speed), stopAtLocation(currentSegment.location), emergencyStop(), powerOn(), and powerOff(). You may use the following abbreviations in your solution: setCS, setSpeed, stopAL, eStop, pOn, and pOff, respectively."""

WUMPLE_fall_2023 = """The watch W-UMPLE combines time keeping with alarm and countdown functionalities. The watch shows the time in hours, minutes, and seconds. The watch has four buttons (A, B, C, and D). Press A to change from the timekeeping mode to the alarm mode. If A is pressed another time, then the watch is in the countdown time mode. If A is pressed one more time, then the watch is back in the timekeeping mode.
Press D to turn on the backlight to illuminate the watch display. The backlight can be turned off by pressing D again and will automatically turn off after 10 seconds.
In the timekeeping mode, the current time is shown. Press C to set the current time. First, the seconds can be set. Press C to rotate from seconds to minutes to hours and back to seconds. When seconds, minutes, or hours can be set, they will flash. Press B to change seconds, minutes, or hours in increments of one. Press A to save the changes, i.e., the seconds, minutes, or hours do not flash anymore and cannot be set and the current time is shown.
In the alarm mode, the current alarm time is shown. Press C to set the alarm time. First, the minutes can be set. Press C to rotate from minutes to hours and back to minutes. When minutes or hours can be set, they will flash. Press B to change minutes or hours in increments of one. Press A to save the changes and return to the timekeeping mode. In the timekeeping mode, press B to turn the alarm on and off. Press B for at least 2 seconds to turn Flash Alert on and off. If Flash Alert is turned on, the backlight will flash for 5 seconds in addition to the alarm time flashing for 5 seconds and the watch beeping for 5 seconds when the alarm goes off. The alarm notifications can be stopped by pressing any button. After the alarm, the watch returns to where it was before the alarm went off.
In the countdown mode, the current countdown time is shown. Press C to set the countdown time. First, the seconds can be set. Press C to rotate from seconds to minutes to hours and back to seconds. When seconds, minutes, or hours can be set, they will flash. Press B to change seconds, minutes, or hours in increments of one. Press A to save the changes and return to the countdown mode. In the countdown mode, press B to start the countdown (if a countdown time is set) and B again to stop the countdown. When the end of the countdown is reached, 0:00:00 will flash for 5 seconds and the watch will beep for 5 seconds. If Flash Alert is turned on, the backlight will also flash for 5 seconds. The countdown notifications can be stopped by pressing any button. After the countdown notifications, the watch is in the countdown mode."""

SSC7_fall_2024 = """The Self-Service Checkout SSC7 is used by supermarkets to allow customers to scan their purchases and pay for them, often without any help of supermarket staff.
As shown in the figure on the right, the SSC7 consists of the following parts: (i) an area to the left to place items that still need to be scanned, (ii) a barcode reader, (iii) a touch screen, (iv) a scale in front of the touch screen to weigh items, (v) an area to the right with an integrated security scale where items are placed that have been scanned, (vi) a payment terminal to pay by credit card, (vii) a printer for the bill, and (viii) a light to indicate to a staff member that they are needed.
The SSC7 Software (SSC7S) interacts with parts (ii) to (viii). The barcode reader provides a scanned number to the SSC7S. The SSC7S uses the touch screen to show all information to the customer, and the customer presses buttons and provides the four-digit product code of items without barcode to the SSC7S. Both scales, the one in the front of the touch screen and the security scale, provide a weight to the SSC7S. The SSC7S sends a payment request to the payment terminal, which sends back a success message with an authorization code, a fail message with an error because the payment failed, or a cancel message because the customer canceled the transaction instead of using their credit card. Furthermore, the SSC7S sends the bill to the printer and turns the light for the staff member on and off.
A customer can either scan the barcode of an item or enter the four-digit product code for items without barcode. If the barcode or the product code do not exist in the system, an error message is shown to the customer. When a correct barcode is scanned, then the item is shown on the touch screen. When a correct product code is entered, the item needs to be weighed and afterwards it is shown with its weight on the touch screen. In both cases (i.e., item with or without barcode), the item must then be placed in the area on the right side for a security weight check. If the weight matches the expected weight, then the system is ready for the next item. If it does not, staff must be called for an override to clear the item from the bill. When it is possible to scan an item and the bill has at least one item, the customer may indicate that they want to remove an item from the bill, which also requires staff to be called for an override to clear the item from the bill.
A customer may also indicate that they brought their own bag(s). Each bag has to be weighed with the security scale. This can be done when it is also possible to scan an item. After a bag is weighed, the number of bags is indicated on the touch screen and the system is ready for the next item.
The customer starts the payment process by pressing the Pay button on the touch screen. If the bill has at least one item, the system sends the payment request to the payment terminal and waits for the payment result. If it is successful, the system prints the bill and readies the system for the next customer. If it is unsuccessful, the system is ready for the next item (and shows an error message if the payment failed).
The customer may cancel the weighing of an item or bag, in which case the system is ready for the next item. When it is possible to scan an item or when the customer is required to place the item (not a bag) in the area on the right side for a security weight check, the customer may also request to cancel everything and start over, which requires staff to be called for an override to clear everything.
When an override is required, the system turns on the light and waits for the staff to enter their override code. If the code is incorrect, an error message is shown. Otherwise, the light is turned off, and either the item or everything is cleared.
When the system is idle for a certain time, the SSC7S receives a timeout warning signal. This only happens when staff has not been called for an override and the payment process has not yet been started. The timeout warning signal starts a 60 second countdown on the touch screen. If the customer presses the Continue button, they continue where they had left off. If the countdown reaches 0, the system clears everything and readies the system for the next customer."""
