printer_winter_2017 = """The printer has a master switch which turns the printer on or off. Once the printer is turned on, a user needs to log in before being able to print or scan a document. To login, a user taps her/his printer card on the printer's card reader. Each printer card has a unique ID. If the printer card is authorized, the user can either choose "scan" or "print". If the printer card is not authorized, a login error message is shown.
For the "print" option, the user presses the start button to print the user's first document in the user's print queue. If there is no document in the print queue, an error message is shown instead of performing the printing task. For the "scan" option, the user presses the start button for the printer to scan an original document, which was placed by the user in the automatic page feeder. The scan is sent to the user's email inbox. If the printer does not detect an original document, an error message is shown instead of performing the scanning task. When the printer is done printing or scanning, the user can print or scan the next document. The user may also stop the printing/scanning task at any time by pressing the stop button. The user is allowed to logoff either before or after a printing/scanning task but not while the printer is in the middle of a printing/scanning task.
If there is a paper jam, the printer will suspend the printing/scanning task to allow the user to clear the paper jam. The user may then either cancel the printing/scanning task or resume it. In case the printer runs out of paper during a printing task, the printer suspends the printing task to allow the user to resupply paper. The user may then either cancel the printing task or resume it."""

spa_manager_winter_2018 = """The SpaManager allows saunas and Jacuzzis to be controlled from a central management point. With SpaManager it is possible to turn a sauna or Jacuzzi on and off.
When a sauna is turned on, the stove in the sauna heats until a temperature of 90°C is reached, at which point the stove stops heating until the temperature falls below 85°C and consequently the stove starts heating again. As a safety feature, a humidity sensor monitors the sauna and activates a fan when the humidity exceeds the safety threshold of 40% for more than 3 minutes. The fan turns off automatically after 5 minutes. SpaManager also controls whether eucalyptus-infused water is poured over the stove to increase the humidity. Upon request from the user, a predetermined amount of water is dispersed, if the humidity is below the safety threshold and the fan is not active. At most, water is dispersed once every 15 minutes.
When a Jacuzzi is turned on, the jets of the Jacuzzi eject water at level 1 (the low pressure setting). This can be increased first to level 2 (medium pressure setting) and then to level 3 (high pressure setting). Similarly, the level can be reduced gradually from the highest to the lowest. Furthermore, the user can choose from twenty five different ejection patterns, which determine the order, frequency, and duration of active jets. All ejection patterns work for all three pressure levels. The Jacuzzi comes with a pause feature, which stops the jets from ejecting water for two minutes. The Jacuzzi can also be controlled via a panel attached to the Jacuzzi in the same way as it is controlled remotely from the central management point."""

dishwasher_winter_2019 = """A dishwasher comes with various programs that govern how the dishwasher cleans dishes. The user may select one of the programs, adjust the drying time, and press the start button to start the selected program.
When a dishwasher is started, water is first taken from the water intake pipe. Then, the dishes are washed for 10 minutes and the water is drained. These steps are repeated a certain number of times depending on the chosen dishwasher program. Afterwards, the dishwasher dries the dishes with hot air. By default, the standard drying time of 20 minutes is used. However, the drying time may be extended to 40 minutes at any point during the dishwasher program. The drying time may also be reduced back to the default time but only as long as the drying phase has not started. When the dishwasher is active, its door is locked until the start of the drying phase. It is possible to open the door during the drying phase. When this happens, the drying phase is suspended. The drying phase continues if the door is closed within 5 minutes of opening it. If the door stays open longer, then the dishwasher does not continue with drying the dishes and ends the dishwasher program."""

chess_clock_fall_2019 = """The digital chess clock has six buttons (each of which corresponds to one event): flip (the large white button on the top), minus, plus, startStop, select (the four blue buttons from left to right below the screen), onOff (at the bottom of the clock, not shown in figure).
After turning on the chess clock (with the onOff button), players can iterate through all the (predefined) timings using the plus and minus buttons, and finally select the designated timing by the select button. A timing option has a predefined base time (minutes and seconds) and an increment (in seconds, which can be zero). The game then starts when the startStop button is pressed.
At any time before the game is started, the players can set the clock to match the actual seating of White and Black players using the flip button (e.g. see the placement of the small symbols with the White and Black kings on the screen which can be swapped by pressing the flip button).
When the game is started, White's clock starts counting down (in each second) until the flip button is pressed. At this moment, White's clock stops (and receives a bonus time defined by the increment in the timing option), and Black's clock starts counting down. If the flip button is pressed again, then the same procedure is applied with reversed colors. Both clocks can be stopped by pressing the startStop button, while the game can be continued by pressing the startStop button again. If the clock of the current player counts down to zero, then a flashing flag shall appear on the screen.
The chess clock can be turned off at any time by pressing the onOff button."""

automatic_bread_maker_fall_2020 = """The automatic bread maker has six buttons (each of which corresponds to one event): menu, crust, plus, minus, start, and stop. Furthermore, the bread maker can be turned on and off. The display of the bread maker is out of scope for this state machine.
After turning on the bread maker, a user can select the desired course by iteratively pressing the menu button. The first course is selected by default. At the same time, the user can select the desired kind of crust. The default is medium, which can be changed to dark and then light and then back to medium by pressing the crust button. The bread maker has a delayed start feature, which can be enabled by setting the timer with the plus and minus buttons. Initially, the delayed start feature is not enabled. Each time the plus button is pressed, the timer is increased by 10 minutes up to a maximum of 18 hours. The minus button decreases the timer by 10 minutes.
The start button initiates the baking process or the countdown of the timer in case a timer is set for a delayed start. The baking process consists of the kneading, rising, baking, and warming phases. The various courses of the bread maker differ in terms of their kneading, rising, and baking times. For the kneading phase, a motor is started with the internal startKneading() command. The motor is stopped with the internal stopKneading() command at the end of the kneading phase. During the rising phase, the bread maker does not do anything to the dough. The baking temperature is controlled by the internal heat() command during the baking phase. Each course has a 60 minute warming phase that starts after the baking phase and keeps the bread maker at a set temperature with the internal warm() command. At the end of the warming phase, the bread maker automatically returns to the course selection stage. At any time during the baking process or during the countdown, the stop button also returns the user to the course selection stage."""

thermomix_fall_2021 = """The Thermomix TM6 is an all-in-one kitchen appliance that preps ingredients and cooks them to perfection.
On delivery, the Thermomix TM6 is set to transportation mode. When the selector (button) is pressed to start up the Thermomix TM6 for the first time, the transportation mode is automatically deactivated, and the home screen is shown. To turn the Thermomix TM6 off, hold the selector down for at least five seconds until a message appears to confirm that the Thermomix TM6 is switching off. You can then release the selector. If the Thermomix TM6 has been turned off, pressing the selector turns it back on and the home screen is shown. To save energy, the Thermomix TM6 switches off automatically after 15 minutes when not in use. A message appears for the last 30 seconds, allowing automatic shutdown to be canceled and the home screen to be shown (by selecting cancel on the appliance's screen or by removing the cooking bowl).
To cook a meal, select a recipe on the screen and then select start to follow the step-by-step instructions. First, add ingredients as instructed. The integrated scale weighs them and allows the next step only if the correct amount has been added. Continue to the next step by selecting next on the screen. The Thermomix TM6 chops the ingredients for as long as and at the speed required for the recipe. When the chopping step is done, select next for the Thermomix TM6 to start the cooking step. Again, the Thermomix TM6 cooks the meal at the temperature and time required for the recipe. At the end of any recipe step, the Thermomix TM6 may prompt you to add further ingredients, which are then again weighed, chopped, and cooked. After the last step, the Thermomix TM6 informs you that the meal is ready to be served. When the cooking bowl is removed, the Thermomix TM6 returns to the home screen. It is not possible to cook a meal if the cooking bowl is not correctly placed on the Thermomix TM6.
The selector button raises the following events: selectorPressed (the selector is pressed and released immediately), selectorHeld (the selector is pressed and not released immediately), and selectorReleased (the selector is released after being held)."""

ATAS_fall_2022 = """The Advanced Train Automation System (ATAS) handles the movement of trains across the rail network, i.e., the trains are driverless. The control of the traffic signals, the opening and closing of gates at rail crossings, the setting of turnouts (railroad switches), and the dynamic adjustment of the train's itinerary are out of scope as they are handled by different systems. A train is scheduled several weeks before its departure date, so that passengers can book tickets for the train. The booking process is also out of scope.
The rail network is split into non-overlapping segments. For each segment, the desired train speed is defined. Three types of segments exist: a regular segment, a traffic light segment, and a station segment. The traffic light and station segments also define the coordinates of the location where the train is required to stop (if the light is red or if the station is on the train's itinerary, respectively). While the segments are of variable length, a traffic light or station is always at the end of its segment to allow a train to stop in time if required (i.e., the decision to stop is made when entering the segment). Each traffic light segment or station segment is always followed by a regular segment.
Each train is equipped with three systems that operate continuously and independently of the train as long as the train is active: a Segment Detection System (SDS), a Movement Detection System (MDS), and an Obstruction Detection System (ODS). Each of these systems runs checks every second when a train is active. The SDS detects if the train has entered a new segment and sets the current segment of the train accordingly. The MDS detects if the train is moving or not. The ODS detects whether the railway tracks are obstructed or not and initiates an emergency stop if they are.
At the beginning of its scheduled stop duration, ATAS powers on a train that is waiting at its first station so that the current segment is set to the first segment of the train's itinerary. After the stop duration, ATAS sets the required speed of the train. When the train enters a new segment, the required speed for the segment is set. However, if the segment is a traffic light segment and the light is red, ATAS instead initiates the stopping of the train at the traffic light location. Similarly, if the segment is a station segment, ATAS initiates the stopping of the train at the station location. The actual stopping of the train is confirmed by the MDS in both cases. At a red traffic light, the train waits until the light turns green at which point the ATAS sets the required speed of the train. At a station, the ATAS opens the train doors. The train then waits the scheduled stop duration after which the ATAS closes the train doors and sets the required speed. When the train arrives at its final station, the ATAS waits the scheduled stop duration before powering off the train.
In the case of an emergency, the train stops immediately. You may assume that the train stops in the same segment where an obstruction was detected. Once the train is cleared, the train continues its journey where it left off.
The train is controlled with the help of the following API: setCurrentSegment(segment), setSpeed(currentSegment.speed), stopAtLocation(currentSegment.location), emergencyStop(), powerOn(), and powerOff(). You may use the following abbreviations in your solution: setCS, setSpeed, stopAL, eStop, pOn, and pOff, respectively."""
